// BetterAuth Drizzle schema (Phase 3b) — the auth tables the drizzleAdapter reads.
//
// WHY HAND-AUTHORED (not `@better-auth/cli generate`): the standalone CLI depends
// on `better-sqlite3`, whose native build fails on this Windows toolchain, so the
// CLI cannot run here. These definitions instead mirror BetterAuth 1.6.x's
// CANONICAL core schema (better-auth/dist/db + the drizzle-adapter source): the
// adapter indexes each table by the BetterAuth field name (camelCase), so the
// property keys below MUST be those field names verbatim — `emailVerified`,
// `userId`, etc. The snake_case SQL column names come from `casing: 'snake_case'`
// on the db client (db/client.ts) + drizzle.config.ts, exactly like schema.ts.
// The committed SQL migration is still GENERATED by drizzle-kit from this file
// (AC-3b-2: no hand-written SQL). Correctness is verified empirically by running
// sign-up/sign-in against real Postgres (see the seed + verification steps).
//
// TABLE-NAME COLLISION: the domain schema already owns `session` (training
// sessions), so BetterAuth's auth-session table is named `auth_session` at the
// SQL level here. BetterAuth still addresses it by its model key `session` (see
// the adapter `schema` mapping in lib/auth.ts) — the literal SQL name is taken
// from this Drizzle object, so the two `session`s never collide in Postgres.
//
// Custom fields (role/trainerId/clientId) come from user.additionalFields in
// lib/auth.ts — role drives the guard + landing; trainerId/clientId link a login
// to its domain row (this is what RETIRES EXPO_PUBLIC_TRAINER_ID).

import { boolean, pgTable, text, timestamp } from 'drizzle-orm/pg-core';

// ---------------------------------------------------------------------------
// user — BetterAuth identity. `id` is a BetterAuth-generated string (NOT a uuid);
// createdAt/updatedAt/emailVerified are supplied by BetterAuth on write (the
// defaults below are defensive only). role/trainerId/clientId are the
// additionalFields (input:false — set server-side via seed / provisioning).
// ---------------------------------------------------------------------------
export const user = pgTable('user', {
  id: text().primaryKey(),
  name: text().notNull(),
  email: text().notNull().unique(),
  emailVerified: boolean().notNull().default(false),
  image: text(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  // additionalFields (lib/auth.ts). role defaults to 'client' at the app layer;
  // kept nullable here (BetterAuth applies the default on insert).
  role: text(),
  trainerId: text(),
  clientId: text(),
});

// ---------------------------------------------------------------------------
// auth_session — BetterAuth session (renamed from `session` to avoid the domain
// collision). Addressed by BetterAuth under the model key `session`.
// ---------------------------------------------------------------------------
export const session = pgTable('auth_session', {
  id: text().primaryKey(),
  expiresAt: timestamp({ withTimezone: true }).notNull(),
  token: text().notNull().unique(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  ipAddress: text(),
  userAgent: text(),
  userId: text()
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
});

// ---------------------------------------------------------------------------
// account — credential/provider rows (email+password stores the hash in
// `password`; OAuth would populate the token columns).
// ---------------------------------------------------------------------------
export const account = pgTable('account', {
  id: text().primaryKey(),
  accountId: text().notNull(),
  providerId: text().notNull(),
  userId: text()
    .notNull()
    .references(() => user.id, { onDelete: 'cascade' }),
  accessToken: text(),
  refreshToken: text(),
  idToken: text(),
  accessTokenExpiresAt: timestamp({ withTimezone: true }),
  refreshTokenExpiresAt: timestamp({ withTimezone: true }),
  scope: text(),
  password: text(),
  createdAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).notNull().defaultNow(),
});

// ---------------------------------------------------------------------------
// verification — email-verification / reset tokens.
// ---------------------------------------------------------------------------
export const verification = pgTable('verification', {
  id: text().primaryKey(),
  identifier: text().notNull(),
  value: text().notNull(),
  expiresAt: timestamp({ withTimezone: true }).notNull(),
  createdAt: timestamp({ withTimezone: true }).defaultNow(),
  updatedAt: timestamp({ withTimezone: true }).defaultNow(),
});
